changelog:
  categories:
    - title: Added
      labels:
        - add
    - title: Changed
      labels:
        - change
    - title: Deprecated
      labels:
        - deprecate
    - title: Fixed
      labels:
        - fix
    - title: Removed
      labels:
        - remove
    - title: Security
      labels:
        - security
    - title: Others
      labels:
        - '*'
