name = "hono-example-serve-static"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-01-09"

[site]
bucket = "./"
entry-point = "./"