name: 'Performance Measures'
description: 'Run type check and bundle size performance measurements'

inputs:
  typescript-impl:
    description: 'TypeScript implementation to use: "tsc" (Current compiler) or "tsgo" (Future compiler implemented in Go)'
    required: true
  target-ref:
    description: 'Target ref (main or auto). Set to "auto" to delegate ref detection to octocov.'
    required: false
    default: 'auto'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun install
      shell: bash

    - name: Exit if unknown typescript-impl
      if: ${{ inputs.typescript-impl != 'tsc' && inputs.typescript-impl != 'tsgo' }}
      shell: bash
      run: |
        echo "::error::Unknown typescript implementation specified: ${{ inputs.typescript-impl }}"
        exit 1

    - name: Performance measurement of type check (tsc)
      if: ${{ inputs.typescript-impl == 'tsc' }}
      run: |
        bun scripts/generate-app.ts
        bun tsc -p tsconfig.build.json --diagnostics | bun scripts/process-results.ts > diagnostics.json
      shell: bash
      working-directory: perf-measures/type-check
      env:
        BENCHMARK_TS_IMPL: tsc

    - name: Performance measurement of type check (typescript-go)
      if: ${{ inputs.typescript-impl == 'tsgo' }}
      run: |
        bun scripts/generate-app.ts
        bun tsgo -p tsconfig.build.json --diagnostics | bun scripts/process-results.ts > diagnostics.json
      shell: bash
      working-directory: perf-measures/type-check
      env:
        BENCHMARK_TS_IMPL: typescript-go

    - name: Performance measurement of bundle check
      run: |
        bun run build
        bun perf-measures/bundle-check/scripts/check-bundle-size.ts > perf-measures/bundle-check/size.json
      shell: bash

    - name: Run octocov
      if: ${{ inputs.target-ref == 'auto' }}
      uses: k1LoW/octocov-action@v1
      with:
        config: perf-measures/.octocov.perf-measures.yml
      env:
        OCTOCOV_CUSTOM_METRICS_BENCHMARK_BUNDLE: perf-measures/bundle-check/size.json
        OCTOCOV_CUSTOM_METRICS_BENCHMARK_TYPE: perf-measures/type-check/diagnostics.json

    - name: Run octocov with custom target ref
      if: ${{ inputs.target-ref == 'main' }}
      uses: k1LoW/octocov-action@v1
      with:
        config: perf-measures/.octocov.perf-measures.main.yml
      env:
        OCTOCOV_GITHUB_REF: 'refs/heads/main'
        OCTOCOV_CUSTOM_METRICS_BENCHMARK_BUNDLE: perf-measures/bundle-check/size.json
        OCTOCOV_CUSTOM_METRICS_BENCHMARK_TYPE: perf-measures/type-check/diagnostics.json
