name = "hono-example-blog"
type = "javascript"
workers_dev = true

compatibility_date = "2022-02-03"

kv_namespaces = [
  { binding = "BLOG_EXAMPLE", preview_id = "", id = "" }
]

[build]
command = "yarn run build"

[build.upload]
format = "service-worker"