locale: "en"
repository: ${GITHUB_REPOSITORY}/perf-measures
coverage:
  if: false
codeToTestRatio:
  if: false
testExecutionTime:
  if: false
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
summary:
  if: true
