name = "hono-example-mustache"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-01-28"

[site]
bucket = "./view"
entry-point = "."