name: autofix.ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  autofix:
    name: autofix
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.19'
      - run: bun install
      - run: bun run format:fix
      - run: bun run lint:fix
      - name: Apply fixes
        uses: autofix-ci/action@v1
        with:
          commit-message: 'ci: apply automated fixes'
