name: cr
on:
  push:
    branches: [main]
    tags: ['!**'] # Avoid publishing on tags
  pull_request:
    types: [opened, synchronize, labeled] # Run on PR creation, updates, and when labels are added

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }} # Concurrency group for each PR
  cancel-in-progress: true # Cancel in progress builds for the same PR

permissions:
  contents: read

jobs:
  publish:
    if: github.repository == 'honojs/hono' && (github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'cr-tracked'))
    runs-on: ubuntu-latest
    name: 'Publish: pkg.pr.new'
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: '.tool-versions'

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: '.tool-versions'

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Publish to StackBlitz
        run: |
          bun pkg-pr-new publish --compact
