name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  jsr:
    name: publish-to-jsr
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2
        with:
          deno-version-file: '.tool-versions'
      - run: deno install --no-lock --allow-scripts
      - name: Publish to JSR
        run: deno run -A jsr:@david/publish-on-tag@0.1.4
